### ISSUE TITLE
when clicking play, program refuses to respond to input 

### ISSUE THREAD

**Issue by KianWalsh** [pkmniako/OtherWorlds_Public#1]
while launching the game, with Kopernicus installed, the start game menu of the title screen refuses to respond to mouse input. The game still runs, and the Kerbin still rotates, but any attempt to select start, resume or any other menu items dose nothing.  I can verify that Kopernicus works alone, and I tried remove every other mod in my gamedata to see if they're interfering.

logs from MM and Kopernicus. 
[Kopernicus.log](https://github.com/pkmniako/OtherWorlds_Public/files/10714604/Kopernicus.log)
[ModuleManager.log](https://github.com/pkmniako/OtherWorlds_Public/files/10714606/ModuleManager.log)

**Comment by pkmniako** [comment]
Known issue. Custom code doesn't cause it, meaning it has to be Kopernicus Configuration Files.

Buttons are offsetted to the left of the text, sometimes even going out of the screen. Alternatively you can use the Arrow Keys and Enter Key to navigate the menu.

Doesn't appear to affect the main menu, but only the "Resume Game" section.

I wanted to talk with Kopernicus' maintainers to try to solve this problem, but thanks for the input.

**Comment by KianWalsh** [comment]
It also occurs when you quit to menu, even on the main menu

**Comment by pkmniako** [comment]
Fixed on [Kopernicus Release 159](https://github.com/Kopernicus/Kopernicus/releases/tag/release-159)
