### ISSUE TITLE
Mod breaks the R&D Center Archives

### ISSUE THREAD

**Issue by Lithobraker** [pkmniako/OtherWorlds_Public#2]
As the title says, using this mod causes the R&D Center Archives to break. I've tested it out with new save files, and narrowed it down to this mod as the cause.
![tow_bug_2](https://user-images.githubusercontent.com/6070905/224394058-46784a7c-7284-4eec-9758-025e3070da7c.png)
No matter how much research I conduct, the archives are always empty, and Wernher is always replaced with this odd little sprite of a Kerbal. When I disable Other Worlds, the archives work again and Wernher returns.

**Comment by pkmniako** [comment]
Bug can be recreated. It's not tied to the custom code, but to the configuration files.

KSP.log sheds some light:
```
NullReferenceException: Object reference not set to an instance of an object
	KSP.UI.Screens.RDArchivesController.AddPlanetRecursively (PSystemBody parent, PSystemBody body, System.Single offset_pos, System.Single offset_pos_inc, System.Int32 hierarchy_level) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	KSP.UI.Screens.RDArchivesController.AddPlanetRecursively (PSystemBody parent, PSystemBody body, System.Single offset_pos, System.Single offset_pos_inc, System.Int32 hierarchy_level) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	KSP.UI.Screens.RDArchivesController.AddPlanets () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	KSP.UI.Screens.RDArchivesController.Start () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Looks like KSP is getting confused by the new planets?

**Comment by Lithobraker** [comment]
> Bug can be recreated. It's not tied to the custom code, but to the configuration files.
> 
> KSP.log sheds some light:
> 
> ```
> NullReferenceException: Object reference not set to an instance of an object
> 	KSP.UI.Screens.RDArchivesController.AddPlanetRecursively (PSystemBody parent, PSystemBody body, System.Single offset_pos, System.Single offset_pos_inc, System.Int32 hierarchy_level) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
> 	KSP.UI.Screens.RDArchivesController.AddPlanetRecursively (PSystemBody parent, PSystemBody body, System.Single offset_pos, System.Single offset_pos_inc, System.Int32 hierarchy_level) (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
> 	KSP.UI.Screens.RDArchivesController.AddPlanets () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
> 	KSP.UI.Screens.RDArchivesController.Start () (at <39c0323fb6b449a4aaf3465c00ed3c8d>:0)
> 	UnityEngine.DebugLogHandler:LogException(Exception, Object)
> 	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
> 	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
> ```
> 
> Looks like KSP is getting confused by the new planets?

I wish I could shed more light on this issue. I've also just now realized I completely forgot to include my log files- sorry about that. Though for some reason, GitHub won't let me upload my latest log. It may be too big. Let me know if you think my logs would help.

**Comment by pkmniako** [comment]
Problem found. Ice giant was missing a parameter in the configuration files, that made KSP just not be able to render the planet in the RnD Archive.

Update in the following days.

**Comment by Lithobraker** [comment]
> Problem found. Ice giant was missing a parameter in the configuration files, that made KSP just not be able to render the planet in the RnD Archive.
> 
> Update in the following days.

I got this reply from R-T-B on the Kopernicus Discord:
"this happens when the planet pack author fails to declare a planet template, and is missing some mystery property.  No one really knows what.  Safe answer is just use a template."
Did you just give it a template, or did you find the specific property it was missing?
