### ISSUE TITLE
MultiStarSolarPanels.cfg & Kopernicus 211 release

### ISSUE THREAD

**Issue by EternalNova** [pkmniako/OtherWorlds_Public#8]
Hello, I'm not really familliar with KSP modding, but I think with the latest Kopernicus releases, there is no need for MultiStarSolarPanels.cfg in Configuration Files. 
With Kopernicus version >208 I'm pretty sure it breaks solar panels. At least it did for me. Basically I updated Kopernicus version from 208 to 211 and after loading the game I got the warnings about module being found more than once as you can see in screenshot (if you need I can upload log file) And after in the game the solar panels were broken, they could not be extended and did not generate EC at all. After that, I downgraded from 211 to 208, which fixed back the solar panels and then upgraded back again and started looking what else might cause problems which led me to the MultiStarSolarPanels.cfg file, I commented every line in file and upon loading back I got no warnings and solar panels were working fine.
![image](https://github.com/user-attachments/assets/6511c0e4-f51c-42b9-82e3-b44b55f4ef3a)

**Comment by FuriousFred** [comment]
I can also confirm that Kopernicus 211 breaks solar panel electricity generation, but only when Other Worlds is installed. I downgraded to -198 as that was the last version before the current OW 1.0.5 patch, but I'll upgrade to -208 as tested by EternalNova.

**Comment by Aebestach** [comment]
Just remove `OtherWorldsReboot/ConfigurationFiles/MultiStarSolarPanels.cfg`, because it is the same as the current KOP multi-star mode

**Comment by pkmniako** [comment]
File removed in newest release
